import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Paul Portfolio',
  description: 'Generated by paulOlawalee',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-[80%] m-auto '>
            {children}
        </div>
      
        </body>
    </html>
  )
}
